[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_escrow = "5R7pWP5Ho263MdpcW92Md3EVSpH99gLcPZ9Ereod1mAu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
